.travis.yml
lazyClient.go
lazyServer.go
multistream.go
multistream_test.go

* Split lazy server and lazy client types. They're very different and do very different things.
* Combine lazy client write with handshake. This allows us to negotiate and write all in one go.
I'm *not* happy with the server-side logic but couldn't find a nice, clean way to fix it so I left it as it was (mostly). Eventually, we'll have to switch to a new protocol anyways because this one isn't sound.

fix benign race and clean up handshake logic

---

client.go
multistream_test.go

Needed for QUIC support.
We have to use a TCP connection instead of `net.Pipe()` in the multistream tests, since the connections returned by `net.Pipe()` are not buffered, so it won't work if both sides write before reading.

first write, then read during the handshake

---

client.go

Given that *both* sides now try to write the multistream handshake out before reading, we need to do it asynchronously. Otherwise, we can deadlock (depending on the protocol).
In practice, this shouldn't be an issue but I'm not sure if we can really *guarantee* that.
This fix *does* cost us an ephemeral goroutine but I'm not sure if we can get away from that.

write asynchronously when handshaking

---

lazyClient.go
multistream.go

Profiling relays reveals that a whopping 56% of the allocations are BufferedWriters, and this is the only place where we actually use them.
This pools the allocation to avoid trashing the gc.

pool BufferedWriter allocations

---

client.go

This makes the non-lazy negotiator act *slightly* more like the lazy one.
Instead of sending the multistream header and *then* the protocol header, it
sends them both in the same packet.
This *shouldn't* cause any issues but we should still think carefully about
whether or not this is worth it. It:
1. Sends fewer packets.
2. Saves half an RTT.

send fewer packets by combining writes when possible

---

multistream.go

This PR is part of a batch across go-libp2p repos to consolidate abstractions, interfaces and core types into [libp2p/go-libp2p-core](https://github.com/libp2p/go-libp2p-core). See branch [`consolidate-skeleton`](https://github.com/libp2p/go-libp2p-core/tree/consolidate-skeleton) there.
Work is being performed in the `consolidate-skeleton` branch across repos.
In this PR, we make backwards-compatible adjustments for go-multistream to conform to the new [`protocol.Negotiator` interface](https://github.com/libp2p/go-libp2p-core/blob/master/protocol/switch.go#L53).
---
Merge strategy: squash and rebase.

interface adjustments for abstraction friendliness

---

client.go
multistream.go
multistream_test.go

fixes #41
Note: To make the `Ls` helper actually _useful_, it now performs the handshake
internally. Really, this library isn't built for interactive use while `ls` _is_
so the interfaces are going to be kind of wonky.

ls: make ls more consistent with other protocols

---

lazyClient.go
lazyServer.go
multistream.go
multistream_test.go

First, this change exposes a Flush function so users can flush a handshake without writing or reading. We need this in libp2p to flush before closing for writing.
Second, this change flushes on Close. We can drop the read half of the handshake, but we need to send the write half. Otherwise, we could end up with the following situation:
1. A: Send data.
2. B: Receive data.
3. B: Close the stream. (no flush)
4. A: Wait for an EOF from the stream (ensure receipt of data).
5. B: ERROR: the stream was closed but no multistream header was sent.
This is _slightly_ unfortunate as Close should ideally never block. But close _is_ allowed to flush and the alternative is to spawn a goroutine.

improve negotiation flushing

---

multistream_test.go

reduce the number of streams in the stress tests, fix error handling

---

client.go
multistream.go
multistream_test.go

For https://github.com/libp2p/go-libp2p/issues/1039.
Implements this Spec: https://github.com/libp2p/specs/pull/196
TBD:

Implement simultaneous open extension

---

client.go

See https://github.com/libp2p/specs/pull/321.
This is ok since the last libp2p release (v0.13.0) included go-multistream v0.2.0, which didn't have simultaneous open support yet.
cc @mxinden (can't add you as a reviewer here)

change the simultaneous open protocol to /libp2p/simultaneous-connect

---

client.go
multistream.go
multistream_test.go

As far as I can tell, `ls` is the main reason we're using a 64 kB buffer when reading tokens in https://github.com/multiformats/go-multistream/blob/711a0aaf37fdd541271c6c829083c59247219108/multistream.go#L440-L444.
Given that this protocols is used by neither libp2p, IPFS or lotus, and we're in the process of replacing multistream with Protocol Select anyway, it seems safe to remove, especially given that this doesn't seem to be part of the [spec](https://github.com/libp2p/specs/blob/master/connections/README.md).

remove unused ls command

---

multistream.go

Now that `ls` is removed, there's no need for super large messages any more.

reduce the maximum read buffer size from 64 to 1 kB

---

client.go
multistream.go

Part of https://github.com/libp2p/go-libp2p/issues/1389

catch panics

---

multistream.go
multistream_test.go

We would fail to negotiate if we couldn't echo back the protocol id. It should be valid to fail to write back the protocol ID and return the negotiate stream so that the caller may read data from the stream.
This pattern is common when a dialer opens a new stream, sends some data, then closes the stream immediately. (bitswap, graphsync). Without this there's really nothing a caller can do besides sleep enough to let the other side send it's multistream protocol response.
Fixes: 
- https://github.com/ipfs/go-ipfs/pull/9038#pullrequestreview-1003663418
- https://github.com/ipfs/go-graphsync/pull/388
This is a regression from https://github.com/multiformats/go-multistream/pull/85. NegotiateLazy would not fail to negotiate for the listener.
r? @marten-seemann cc @Stebalien

Ignore error if can't write back echoed protocol in negotiate

---

multistream.go
multistream_test.go

A continuation of https://github.com/multiformats/go-multistream/pull/87. It's the same thing, but we didn't account for the case the the stream is closed so early we don't get a chance to write our multistream select protocol id.
Worth noting that the old NegotiateLazy also ignored this error, so it should be a safe change (since this is the same as the old behavior).

Ignore error if can't write back multistream protocol id

---

multistream.go
multistream_test.go

We're removing this method from the interface in libp2p in https://github.com/libp2p/go-libp2p/pull/1869.

remove MultistreamMuxer.NegotiateLazy

---

README.md
client.go
lazyClient.go
multistream.go
multistream_test.go

This change allows users to use their custom types instead of translating to and from string type
Related to: https://github.com/libp2p/go-libp2p/issues/1886

Make MultistreamMuxer and Client APIs generic

---

client.go
lazyClient.go
multistream_test.go

Fixes: https://github.com/multiformats/go-multistream/issues/94

Add not supported protocols to returned errors

---

client.go
multistream_test.go

Callers expect to be able to check if an error is a ErrNotSupported. The generics change things so we need to explicitly add a `.Is` method.

Fix errors Is checking

---

client.go

New error type to let the caller know about unrecognized responses. Useful in detecting TCP simultaneous open errors.

feat: New error to highlight unrecognized responses

---

lazyClient.go
multistream_test.go

fixes https://github.com/libp2p/go-libp2p/issues/3038

fix: finish reading handshake on lazyConn close

---

lazyClient.go
multistream_test.go

Changes the sync.Once usage to a synctest friendly once version. More context on synctest here: https://go.dev/blog/synctest.
synctest doesn't consider code blocked by a mutex as "durably blocked." This makes sense for the common case where a mutex protects some critical section of code that runs quickly. In multistream's case the protected section of a mutex does IO (it finishes the handshake). This would mean that you would end up deadlocked in a synctest bubble because one goroutine would be waiting to acquire the lock, but the goroutine that would free the lock wouldn't be able to make progress because no network IO or time would happen.
With this change basichost works with synctest.

refactor(lazyClientConn): Use synctest friendly once func
